version: '3'
services:
  api:
    # build:
    #   context: ./
    #   dockerfile: micro-chimp.Dockerfile
    #   args:
    #     SITE_NAMES_FILE: docker/site_names.yml
    image: blainehansen/micro-chimp
    links:
      - database
    ports:
      - "5050:5050"
    environment:
      - MAILGUN_AUTH=fake
      - POSTGRES_USER=rust_server_user
      - POSTGRES_PASS=password
    tty: true
    command: /server/micro-chimp

  database:
    # build:
    #   context: ./
    #   dockerfile: micro-chimp-postgres.Dockerfile
    #   args:
    #     SITE_NAMES_FILE: docker/site_names.yml
    image: blainehansen/micro-chimp:postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=asdf
    ports:
      - "5432:5432"
    # volumes:
    #   - ./.configs/.keys.go-db.txt:/keys/.go-db-key
    command: postgres -c 'max_wal_size=2GB'

# https://www.digitalocean.com/community/tutorials/how-to-self-host-reviewninja-on-digitalocean-using-docker-and-coreos
