# each of these entries is for
<url>: # add your base url here (example.com)
  from_email: <account>@<url> # (no-reply@example.com)
  # this text will be used as the subject of the initial verification email
  subject_text: "Hello! Welcome to <site_name>!"
  # and this text will be the body
  body_text: |
    Hello! Thank you for signing up to join <site_name>.

    Click this link to validate your email:
    https://<url>/validate-email?t={verification_token}
  # this last link is formatted in the way the micro-chimp codegen script expects
  # only change the url! (https://example.com/validate-email?t={verification_token})

# feel free to add as many as you want!
# micro-chimp can be used for many different sites at the same time
